### PR TITLE
Fix "%d" being used with strings

### LINKED ISSUE #15: The GOMAXPROCS environment variable is of type string rather than an number
https://github.com/uber-go/automaxprocs/blob/946a8391268aea0a60a86403988ff3ab4b604a83/maxprocs/maxprocs.go#L100

The above format flag of the environment variable should be %s rather than %d

### PR DESCRIPTION
**Pull request by prashantv**
Rather than specifying the type in the format, we can rely on the
default formatting using "%v".

Fixes #15.

### CODE REVIEW

File: maxprocs/maxprocs.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ func Set(opts ...Option) (func(), error) {
 	// `runtime.GOMAXPROCS()` with the current process' CPU quota if the OS is
 	// Linux, and guarantee a minimum value of 2 to ensure efficiency.
 	if max, exists := os.LookupEnv(_maxProcsKey); exists {
-		cfg.log("maxprocs: Honoring GOMAXPROCS=%d as set in environment", max)
+		cfg.log("maxprocs: Honoring GOMAXPROCS=%v as set in environment", max)
```
Comment (robbertvanginkel) [inline maxprocs/maxprocs.go]: Maybe because this is an env string, this could be `%q` to quote the string?
